import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Spline from '@splinetool/react-spline';

export default function Home() {
  return (
    <>
      <Head>
        <title>Eli Art of the Web Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spline className={styles.spline} scene="https://prod.spline.design/jwBUVw7L85y0WV4p/scene.splinecode" />
    </>
  )
}
